### ISSUE TITLE
Problem in saving incremental classifiers!

### ISSUE THREAD

**Issue by palash247** [Waikato/meka#10]
I am trying to train an incremental classifier and I am planning to update the classifier in future with new datasets as soon as they are available. For that, I need to save the trained incremental classifier. Saving a trained classifier can be done by using -d option but the option is not working in case of incremental classifiers. Following is the error I'm getting:

`C:\Users\Palash\Dropbox\Project ME\java\meka-release-1.9.0>java -Xmx1024m -cp "./lib/*" meka.classifiers.multilabel.incremental.BRUpdateable -d classifier.dump -verbosity 5 -t train_dmoz_computers_dataset.arff -W weka.classifiers.meta.MOA -- -B moa.classifiers.trees.HoeffdingAdaptiveTree -output-debug-info`

`Evaluation exception (java.lang.Exception: Illegal options: -d classifier.dump ); failed to run experiment
java.lang.Exception: Illegal options: -d classifier.dump
        at weka.core.Utils.checkForRemainingOptions(Utils.java:542)
        at meka.classifiers.multilabel.incremental.IncrementalEvaluation.evaluateModel(IncrementalEvaluation.java:83)
        at meka.classifiers.multilabel.incremental.IncrementalEvaluation.runExperiment(IncrementalEvaluation.java:45)
        at meka.classifiers.multilabel.incremental.BRUpdateable.main(BRUpdateable.java:72)`

If saving classifier is not yet supported by incremental learners in meka, then how can I tweak it to get the job done.

**Comment by fracpete** [comment]
That wasn't supported, so I've added the -d/-l options to the incremental evaluation. You can download a snapshot with this functionality from [here](https://adams.cms.waikato.ac.nz/snapshots/meka/).
NB: Only minimal testing was performed.

**Comment by palash247** [comment]
Now getting the array index out of bound exception when I use option -d with following mentioned command. However, the same command executes completely if I don't use option -d. Following is the error:

![meka error](https://cloud.githubusercontent.com/assets/10260127/16058704/5996c6e6-329d-11e6-9182-97d7ff1d11e5.PNG)

**Comment by fracpete** [comment]
Copy/paste of text rather than screenshot would be appreciated. Retyping is prone to introducing typos.

I cannot reproduce the problem with the *Music.arff* dataset:
```bash
meka.classifiers.multilabel.incremental.PSUpdateable -t Music.arff -d classifier.dump -verbosity 5 -I 1000 -support 10 -P 0 -N 0 -W weka.classifiers.bayes.NaiveBayesUpdateable
```

However, I fixed a problem with the options: `-S` was already defined in the super class (for the *seed* value) and couldn't be used for the *support*. The option for supplying the *support* is now `-support` (as you can see in the above command-line string).
