### ISSUE TITLE
Problem in prediction from trained incremental model.

### ISSUE THREAD

**Issue by palash247** [Waikato/meka#11]
I was successful in generating predictions for single unlabeled data instance by using non-incremental trained model as follows:
`java -Xmx6000m -cp "./lib/*" meka.classifiers.multilabel.PS -l dump_ps_nbu_dmoz -t dmoz_computers_2000_175.arff -verbosity 5 -T temp_test.arff`
`== Individual Errors`

`|==== PREDICTIONS (N=1.0) =====>`
`|    1 [] [28, 105]`
`|==============================<`
Then I tried it for incremental traind model and I got this error:
`java -Xmx6000m -cp "./lib/*" meka.classifiers.multilabel.incremental.PSUpdateable -l gui_dmoz_ps_nb -t dmoz_computers_2000_175.arff -verbosity 5 -T temp_test.arff
Evaluation exception (java.lang.Exception: Illegal options: -T temp_test.arff ); failed to run experiment
java.lang.Exception: Illegal options: -T temp_test.arff `
	`at weka.core.Utils.checkForRemainingOptions(Utils.java:542)`
	`at meka.classifiers.multilabel.incremental.IncrementalEvaluation.evaluateModel(IncrementalEvaluation.java:107)`
	`at meka.classifiers.multilabel.incremental.IncrementalEvaluation.runExperiment(IncrementalEvaluation.java:45)`
	`at meka.classifiers.multilabel.incremental.PSUpdateable.main(PSUpdateable.java:204)`

I don't know if I'm making any mistake cause I haven't found any documentation for this. Is there any other way to predict using incremental models?

**Comment by fracpete** [comment]
`-T` option for supplying a test set was not available for incremental evaluation. Just submitted fix that adds this option: performs testing in batch-fashion.

**Comment by palash247** [comment]
Hope so, it will be available for prequential evaluation too.

**Comment by fracpete** [comment]
Maybe I wasn't clear. The `-t` option used with an incremental learner performs automatically prequential evaluation (first evaluate, then update). Providing a test set via `-T` tests the current state of the learner (one that was either loaded from disk with `-d` and/or updated with `-t`) in batch-fashion and outputs those statistics.

**Comment by palash247** [comment]
Sorry for not responding then, I was so selfish back then. I haven't even appreciated the quick response. I got the fixed and moved ahead with my work.
