### ISSUE TITLE
Missing javadoc online

### ISSUE THREAD

**Issue by brodin** [Waikato/meka#13]
At http://meka.sourceforge.net/ the link to "The API reference." points towards http://meka.sourceforge.net/api-1.7/index.html all tough 1.9.0 is the current version. Is it possible to host the current javadoc as well?

**Comment by jmread** [comment]
I have now added the 1.9 api docs: http://meka.sourceforge.net/api-1.9/index.html

**Comment by brodin** [comment]
Lovely! Thanks! 👍
