### ISSUE TITLE
have Meka contains the method describled in "deep learning for multi-label classification" 

### ISSUE THREAD

**Issue by rong111** [Waikato/meka#14]
Hello,

I am now doing some works of multilabel deep learning, and have noticed the paper "deep learning for multi-label classification", Jesse Read and Fernando Perez-Cruz,  2014.  Are the functions related to this paper already included to the Meka package?

Thanks very much

**Comment by jmread** [comment]
Hi,

Yes, you may want to have a look at the `meka.classifiers.multilabel.BPNN` and `java meka.classifiers.multilabel.DBPNN`, and `meka.classifiers.multilabel.meta.DeepML` classes. Some examples on how to run these methods are given [on MEKA's sourceforge page](http://meka.sourceforge.net/methods.html).
