### ISSUE TITLE
Difference EnsembleML and BaggingML

### ISSUE THREAD

**Issue by alexgcsa** [Waikato/meka#39]
Hello,

I would like to know what is the difference between the meta multi-label classifiers EnsembleML and BaggingML. Is there a reference for EnsembleML?

Thanks,

Alex de Sá

**Comment by jmread** [comment]
Hi, the only difference is that BaggingML allows for sampling with replacement for each model, whereas EnsembleML is a simple ensemble (a simple cut of the training set for each model, i.e., sampling without replacement).

**Comment by alexgcsa** [comment]
Thank you very much.
