### ISSUE TITLE
REUTERS-K500-EX2.arff reference

### ISSUE THREAD

**Issue by i02momuj** [Waikato/meka#40]
Hello,

I would like to know what is the original reference of the REUTERS-K500-EX2.arff dataset, since I would like to use it in one of my experiments.

Thanks!

**Comment by jmread** [comment]
If I remember correctly, Tsoumakas and Vlahavas describe the process of feature selection on the tmc2007 dataset in their paper "Random k-labelsets: An ensemble method for multilabel classification" , ECML-PKDD, 2007. I applied the same process to one of the Reuters subsets in "Classifier chains for multi-label classification", Mach Learn 2011, to obtain the dataset you mention. The original Reuters data (before preprocessing) is available at http://mulan.sourceforge.net/datasets-mlc.html
