### ISSUE TITLE
Doubts about the algorithms in MEKA

### ISSUE THREAD

**Issue by alexgcsa** [Waikato/meka#42]
Hi,

I have three different (conceptual) doubts about the meta-algorithms. I am trying to understand them.

1) It is said in the documentation that Classification Maximization (CM) is a hard version of Expectation Maximization (EM). What does it mean this statement? What are the differences between them? 

2) The Meta BR (MBR) has the description saying that "BR stacked with feature outputs into another BR". I did not understand it. What do you mean with  this description?

3) In the description of Subset Mapper, it said that this algorithm "maps the output of a multi-label classifier to a known label combination using the hamming distance".  Would it be the hamming distance between what?

Thanks in advance!

Alex de Sá

**Comment by jmread** [comment]
Hi,

- CM does not take into account posterior probabilities (and thus may be used when none are available). This method is not specific to Meka, More details can be found in the literature. 

- In MBR the label predictions of a BR method become the features for a new BR.

- In Subset Mapping, it refers to the Hamming distance between a prediction on a test instance and label combinations (i.e., label subsets) from the training set, it is 'mapped' to the closest one.

Cheers,

Jesse

**Comment by alexgcsa** [comment]
Thanks, Jesse.

I was also checking the code of Four-class pairWise classification algorithm (FW) and I didn't understand so much one of the methods (distributionForInstance) :

https://github.com/Waikato/meka/blob/master/src/main/java/meka/classifiers/multilabel/FW.java

I was wondering if the result (output) of this method  should be the probabilities of the labels. It seems that is just the countings for each possible class. I got a little confused in this point (I changed the name of issue).

Thank you so much again.

Best regards,

Alex de Sa

**Comment by jmread** [comment]
Your understanding of the FW classifier is correct. Probably it would be nicer to divide the counts by a sum to obtain a kind of approximation of the probability (between 0 and 1) for each label. But it is not a requirement, since an appropriate threshold will take care of that.

Regards,

Jesse

**Comment by alexgcsa** [comment]
Alright. I understood what you said. I will possibly do that in the code then.

Best regards,

Alex de Sa
