### ISSUE TITLE
could not initialize the generic properties creator

### ISSUE THREAD

**Issue by liloup1789** [Waikato/meka#44]
When I lauch run.bat, this is the message error : 
could not initialize the generic properties creator
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader 

Could someone help/explain ? 
Thanks

**Comment by fracpete** [comment]
I presume you're using Java 9? Meka doesn't work yet with Java 9. Use Java 8 instead.

**Comment by liloup1789** [comment]
OKay thank you for your answer

**Comment by liloup1789** [comment]
And Will it be a meka update to be compatible with java 9 ?

**Comment by fracpete** [comment]
At some stage. No definitive date.

**Comment by fracpete** [comment]
Release 1.9.2 works with Java 9 and 10.
