### ISSUE TITLE
Homepage is bronken

### ISSUE THREAD

**Issue by gustavoresque** [Waikato/meka#45]
The homepage http://meka.sourceforge.net/ is broken.

**Comment by fracpete** [comment]
Seems to be a sourceforge.net issue at the moment:
https://sourceforge.net/error-404.html

**Comment by fracpete** [comment]
Since sf.net is still down... If you want to download Meka, you can always download a nightly build:
https://adams.cms.waikato.ac.nz/snapshots/meka/

**Comment by gustavoresque** [comment]
Thank you! =]

**Comment by fracpete** [comment]
sourceforge seems to have resolved their issues and the homepage is back online.
