### ISSUE TITLE
Java example (e.g TrainTestSet.java...) execute classifier.buildClassifier  twice.

### ISSUE THREAD

**Issue by vutle** [Waikato/meka#48]
Inside some of the Java examples we called 
classifier.buildClassifier
Inside Evaluation.evaluateModel(...)  classifier.buildClassifier is called again.

If would be good in to flag the classifier that it has been built. Then inside the  Evaluation.evaluateModel check that if classifier.isBuilt() and prevent rebuiding the classifier.

This way we can resuse the evaluationModel function to evaluate a saved model or passed in a prebuilt model just to evaluate.

Regards

**Comment by fracpete** [comment]
The classifier is *only* rebuilt if you pass in training and test set. If you use the overloaded method with just the test instances, then no training occurs:
```java
public static Result evaluateModel(MultiXClassifier h, Instances D_test, String tal, String vop) throws Exception;
```

**Comment by vutle** [comment]
Thanks,
I wanted to display the information about the saved model. So I have created an override function for that  purpose.
