### ISSUE TITLE
Showing model representation in output results for CR, CCP etc

### ISSUE THREAD

**Issue by vutle** [Waikato/meka#49]
Hi
Currently Meka seems to only showing the model output in string for BCC and CC with J48 method.

Setting verbose >= 5 does not show model as string in the output.

Show Graph manually in explorer does display the tree representation of the model.

Question:
  For consistency, if possible, please enable showing model text for CR and other methods.

Thanks

**Comment by vutle** [comment]
I'm currently get around that by
Extend class for CR then add this function.

public String getModelExtend()
	{
		if(m_MultiClassifiers != null)
		{
			StringBuilder sb = new StringBuilder();
			for(int i = 0; i < m_MultiClassifiers.length; ++i)
			{
				sb.append("meka.classifiers.multitarget.CR: Node #" + (i + 1) + "\n\n");
				sb.append(m_MultiClassifiers[i].toString() + "\n");
			}
			return sb.toString();
		}
		
		return "";
	}

Then manually calling getModelExtend() to get the model string summary.

----------

**Comment by fracpete** [comment]
Commit https://github.com/Waikato/meka/commit/14e8648f758f6aa9a0fcee9f644d3fce92058410 implements method `getModel()` in the `BR` superclass.
