### ISSUE TITLE
Adding other weka base classifiers

### ISSUE THREAD

**Issue by mansueli** [Waikato/meka#52]
Is there a way to add other base classifiers on Meka from weka?

**Comment by fracpete** [comment]
You need to be a bit more specific. A lot of meta-classifiers in Meka allow you to switch the Weka base classifier. Please use the Meka mailing list for questions: https://sourceforge.net/p/meka/mailman/

**Comment by fracpete** [comment]
See discussion on mailing list: https://sourceforge.net/p/meka/mailman/meka-list/thread/CP2P152MB1730CC438D37DFB0ECDA2248DB170%40CP2P152MB1730.LAMP152.PROD.OUTLOOK.COM/#msg36423352
