### ISSUE TITLE
Fail to Update Classifier 

### ISSUE THREAD

**Issue by Malsh20** [Waikato/meka#54]
Hi
I tried to use CRUpdateable as classifier, I am building classifier by first 100 instances and then I need to add 1 by one instances and update my classifier but the process of updating create NullPointerException. my code is here:

    try {
            ConverterUtils.DataSource dataSource = new ConverterUtils.DataSource(FILE_PATH); // original dataset
            Instances preparedDataSet = dataSource.getDataSet();
            preparedDataSet = filterUnsupervisedAttributes(preparedDataSet);
            preparedDataSet.setClassIndex(7);

            CRUpdateable classifier = new CRUpdateable();
            RandomForest randomForest = createRandomForest(1);
            classifier.setClassifier(randomForest);

            Instances  trainingInstances = new Instances(dataSource.getStructure()); // temporary dataset for train
            trainingInstances = filterUnsupervisedAttributes(trainingInstances);
            trainingInstances.setClassIndex(7);

            Instances testInstances = new Instances(dataSource.getStructure()); // temporary dataset for test
            testInstances = filterUnsupervisedAttributes(testInstances);
            testInstances.setClassIndex(7);
            int countTestInstances = 0;
            int countTrainInstances = 0;
            boolean firstTrain = true;
            boolean benchTest = true;
            int numInst = preparedDataSet.numInstances();
            for(int row = 123; row < 5021; row++) {
                    Instance trainingInstance = preparedDataSet.instance(row);
                    trainingInstances.add(trainingInstance); // collect instances to use as training
                    countTrainInstances++;
                    if (firstTrain && countTrainInstances%100 == 0 ) {  // train the classifier with the first 100 instances(without any missing values)
                        firstTrain = false;
                        classifier.buildClassifier(trainingInstances);
                    }
                    if(!firstTrain){
                        benchTest = true;
//                      classifier.updateClassifier(trainingInstance);

                        for(int j=row+1;j<row+101;j++){
                            if(benchTest && countTestInstances != 100) { // add next 100 instances to testInstance
                                Instance testInstance = preparedDataSet.instance(j);
                                testInstances.add(testInstance);
                                countTestInstances++;

                                if (countTestInstances % 100 == 0) {
                                    System.out.println("Evaluate CRUpdateable classifier on ");
                                    String top = "PCut1";
                                    String vop = "3";
                                    Result result = Evaluation.evaluateModel(classifier, trainingInstances , testInstances, top, vop);
                                    System.out.println("Evaluation available metrics: " + result.availableMetrics());
                                    System.out.println("Evaluation Info: " + result.toString());
                                    System.out.println("Levenshtein distance: " + result.getValue("Levenshtein distance"));
                                    System.out.println("Type: " + result.getInfo("Type"));
                                    countTestInstances = 0;
                                    benchTest = false;
                                    testInstances.delete();
                                }
                            }
                        }
                    }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

Thanks,
Mali

**Comment by joergwicker** [comment]
The last commit should actually fix that, try to pull from master and use that version.

**Comment by Malsh20** [comment]
I am using meka-1.9.2 which I think it is last version.

**Comment by fracpete** [comment]
Just download a snapshot (aka *daily build*):
https://adams.cms.waikato.ac.nz/snapshots/meka/

**Comment by Malsh20** [comment]
Thanks a lot, I change my lib to this snapshot and it passed the NullPointerException.
But now it can't cast RandomForest to UpdateableClassifier, because I set the model of classifier as Randomforest :
CRUpdateable classifier = new CRUpdateable();
 RandomForest randomForest = createRandomForest(1);
 classifier.setClassifier(randomForest);

when I remove this setting, then as default the model is going to "NaiveBayesUpdateable" which is not for Regression.
Do you have any idea?

**Comment by Malsh20** [comment]
Thanks , this new version solved my problem.
