### ISSUE TITLE
Running MEKA on GPU

### ISSUE THREAD

**Issue by pipinstallyogi** [Waikato/meka#62]
Hello Everyone,
Is it possible to run MEKA on a GPU?
For instance, is it possible to run the CLI for MEKA to somehow use the power of GPU instead of letting it run on CPU? As running MEKA on CPU sometime is very time consuming especially with huge amount of data and some particulat algorithms like kNN or Random forest. I know that Machine learninf takes time but still if there is any way to explore the power of GPU for MEKA it will be great. Can that be done? 
Any inputs will be higly appreciated.
thanks in advance

**Comment by fracpete** [comment]
Unfortunately, no. Meka is pure Java and runs across multiple platforms, but only on the CPU. You'd need to completely rewrite Meka to get GPU support.
