### ISSUE TITLE
  how to apply test dataset in meka 1.9.3 SNAPSHOT

### ISSUE THREAD

**Issue by bhavinpatelgvp** [Waikato/meka#65]
meka.gui.explorer.ClassifyTab
Evaluation failed (train/test split):
java.lang.IllegalArgumentException: Train and test set are not compatible:
Attributes differ at position 2:

  how to apply test dataset in Meka 1.9.3 SNAPSHOT

**Comment by fracpete** [comment]
Train/test datasets must have the exact same structure, i.e., same attribute names and types and for nominal attributes the same order of labels. From the error message, the attributes at index 2 are different between the datasets. Open them in a text editor and/or compare them with a diffing tool (eg command-line diff, or KDiff3, Meld, etc)

**Comment by fracpete** [comment]
Problem seems to be CSV related. See mailing list discussion:
https://sourceforge.net/p/meka/mailman/meka-list/?viewmonth=202004&viewday=21
