### ISSUE TITLE
run error! attach image

### ISSUE THREAD

**Issue by armsterd** [Waikato/meka#69]
![image](https://user-images.githubusercontent.com/43435779/95821796-9a81fc00-0d65-11eb-953b-a41aa6310af4.png)

Hello

I have a problem when run the run.bat program.

MEKA GUI interface is not appeared.

I have JDK - 15 version on computer.

**Comment by fracpete** [comment]
Is this happening with the latest snapshot or is that using the last release?

**Comment by armsterd** [comment]
> Is this happening with the latest snapshot or is that using the last release?

I install and use latest version of MEKA, 1.9.2 today.

Snapshot show a process and result when run the run.bat.

When I double click the run.bat file and it is running 5s. In running, console show some sentence like in image.

After that, It turn off automatically and nothing happened.

**Comment by fracpete** [comment]
Just tried the following JDKs (downloaded as ZIP files from [AdoptOpenJDK](https://adoptopenjdk.net/releases.html)) with the latest [snapshot](https://adams.cms.waikato.ac.nz/snapshots/meka/):
* 1.8
* 11
* 15
All of them work.

Each time, I added the `bin` directory of the extracted zip file to the `PATH` environment variable and also updated the `JAVA_HOME` environment variable accordingly.
I just double-clicked on the `run.bat` file and MEKA started up just fine.

Maybe one of your Weka packages is interfering? Try renaming the `%USERPROFILE%\wekafiles` directory and start up MEKA again.

**Comment by armsterd** [comment]
> Maybe one of your Weka packages is interfering? Try renaming the `%USERPROFILE%\wekafiles` directory and start up MEKA again.

I solved a problem. I think there is a problem in Weka packages.

I remove Weka and all packages installed, then re-install it and Meka.

Thank you for your help :)
