### ISSUE TITLE
MEKA GUI - Performance

### ISSUE THREAD

**Issue by LeguDave** [Waikato/meka#70]
Hello,

I recently started using MEKA GUI and I have a data set similar to your example music.arff. However the 10 fold cross validation of my data set does not terminate or takes longer than 3 hours. Although a default train/split takes roughly half a minute.

My data set has

- 3600 instances
- about 1500 numeric attributes
- Goal: classify the first three attributes (labels)

Configuration

- Binary Relevance 
- J48 -C 0.25 -M 2
- Cross Validation 10 Fold

My questions are:

- Is this an expected computing time?
- If yes, is it because I have that many attributes?
- What can I do to increase performance?

**Comment by fracpete** [comment]
It would be good know whether you can replicate this behavior as it might point to a bug in MEKA.
