### ISSUE TITLE
Capability of MEKA on multi-target regression

### ISSUE THREAD

**Issue by bundit786** [Waikato/meka#73]
Hi,

I just would like to ask if MEKA be able to run multi-target regression problems. If not, is there any software has the capability?

Thank you,
Bundit

**Comment by jmread** [comment]
MEKA does not yet do multi-target regression. I believe by now the Mulan framework does, and if you consider Python, then the scikit-learn library has several methods that can be applied to multi-target regression. 
Best,
Jesse

**Comment by bundit786** [comment]
OK, thank you for supports.
