### ISSUE TITLE
Illegal options -t

### ISSUE THREAD

**Issue by zhangky12** [Waikato/meka#74]
I tried to run the example code simply with

`java -cp "./lib/*" meka.classifiers.multilabel.BR -t data/Music.arff`

But got the following error message

`java.lang.Exception: Illegal options: -t data/Music.arff`

Help will be appreciated.

**Comment by fracpete** [comment]
Looks like recent changes in Weka screwed up the command-line use of Meka. The latest version of Weka enforces the check for remaining options when configuring a classifier now. In Meka's Evaluation class, the classifier got configured before accessing the general command-line options, resulting in this error.

I just committed a fix for that (Meka's Evaluation class now extracts all general options from the options array now before configuring the classifier).

Please download the latest snapshot and try again:
https://adams.cms.waikato.ac.nz/snapshots/meka/

**Comment by zhangky12** [comment]
> Looks like recent changes in Weka screwed up the command-line use of Meka. The latest version of Weka enforces the check for remaining options when configuring a classifier now. In Meka's Evaluation class, the classifier got configured before accessing the general command-line options, resulting in this error.
> 
> I just committed a fix for that (Meka's Evaluation class now extracts all general options from the options array now before configuring the classifier).
> 
> Please download the latest snapshot and try again:
> https://adams.cms.waikato.ac.nz/snapshots/meka/

It works now. Thank you!
