### ISSUE TITLE
[Question] How to use Meka to train and evaluate a semi-supervised model?

### ISSUE THREAD

**Issue by bundit786** [Waikato/meka#82]
Hi Meka Team,

I have some experience using Meka to train and evaluate a supervised model. The semi-supervised model, which is stated to be a capable approach but with little information about how to use it. So, can you give me an example of how train and evaluate a model using a basic technique like pseudo-labelling?

Thank you.

**Comment by bundit786** [comment]
Thank you for getting back. I can now get `CM` in `meka.classifiers.multilabel.meta` using GUI. But for `meka.classifiers.multilabel.SemisupervisedClassifier`, is it available in GUI or only in command line?

**Comment by fracpete** [comment]
`meka.classifiers.multilabel.SemisupervisedClassifier` is just a [Java interface](https://en.wikipedia.org/wiki/Interface_(Java)) for semi-supervised classifiers to implement, not an actual classifier that you can use. `EM` and `CM` implement this interface (and these are the only two semi-supervised classifiers in Meka).

**Comment by fracpete** [comment]
Assumed to be sorted.
